from pydantic import BaseModel, Field
from typing import Optional

class LLMResponseSchema(BaseModel):
    """
    Schema for the response from a Large Language Model (LLM).
    """
    conv_intro: str = Field(
        description = "The opening, friendly commentary or greeting explaining what you are about to do."
    )
    thought_process: str = Field(
        description = "A detailed explanation of the reasoning, steps, or thought process that the LLM used to arrive at the final answer. This should be a comprehensive breakdown of how the LLM analyzed the input and generated the response."
    )
    llm_response:str = Field(
        description = "The final answer or response generated by the LLM, based on the input and the thought process. DO NOT wrap this in triple backticks or any other formatting. It should be the raw response content."
    )
    programming_language:str = Field(
        description = "The programming language of the code snippet provided in the llm_response field. This should be a simple string indicating the language, such as 'python', 'javascript', 'java', etc."
    )
    # Outro refers to the last part of a piece of music, a film, or a video, serving as a closing section. It can also denote the conclusion or epilogue of a literary work.
    conv_outro: Optional[str] = Field(
        default=None,
        description = "The closing commentary or concluding remarks that wrap up the response. This should be a friendly and engaging statement that provides closure to the conversation."
    )